(function(g){var window=this;var uua=function(a,b){var c=[];g.nm(b,function(a){var b;try{b=g.JD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.ID(b)&&c.push(a):c.push(a)},a);
return c},vua=function(a,b){var c=uua(a,b);
(0,g.F)(c,function(a){g.JD.prototype.remove.call(this,a)},a)},o9=function(a,b){g.FS.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.X=a;this.B=!1;this.G={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},wua=function(a){return a.H?a.F+((0,g.E)()-a.A)/1E3:a.F},xua=function(){var a=g.lH;
vua(a,a.g.Nd(!0))},p9=function(a){g.OH.call(this,"ScreenServiceProxy");
this.Uc=a;this.o=[];this.o.push(this.Uc.$_s("screenChange",(0,g.z)(this.VP,this)));this.o.push(this.Uc.$_s("onlineScreenChange",(0,g.z)(this.tM,this)))},q9=function(a){g.BH("cloudview",a)},yua=function(a){q9("setApiReady_ "+a);
g.t("yt.mdx.remote.cloudview.apiReady_",a,void 0)},r9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},zua=function(a){g.FG[a]&&(a=g.FG[a],(0,g.F)(a,function(a){g.DG[a]&&delete g.DG[a]}),a.length=0)},s9=function(){return g.u("yt.mdx.remote.connection_")},t9=function(a){g.t("yt.mdx.remote.connectData_",a,void 0)},Aua=function(a){g.t("yt.mdx.remote.currentScreenId_",a,void 0)},u9=function(){return g.u("yt.mdx.remote.currentScreenId_")},w9=function(){if(!v9){var a=g.u("yt.mdx.remote.screenService_");
v9=a?new p9(a):null}return v9},x9=function(a){g.t("yt.mdx.remote.cloudview.initializing_",a,void 0)},y9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},z9=function(a){q9("setCastInstalled_ "+a);
g.nH("yt-remote-cast-installed",a)},A9=function(a){g.BH("cloudview",a)},Bua=function(a,b){r9().init(a,b)},B9=function(){return!!g.oH("yt-remote-cast-installed")},Cua=function(){q9("dispose");
var a=r9();a&&a.dispose();g.t("yt.mdx.remote.cloudview.instance_",null,void 0);yua(!1);g.HG(C9);C9.length=0},Dua=function(){var a=window.document.createElement("a");
g.Qd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},Eua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Fua=function(a){var b=g.BG();
if(b)if(b.clear(a),a)zua(a);else for(var c in g.FG)zua(c)},D9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},F9=function(a){var b=s9();
t9(null);a||Aua("");g.t("yt.mdx.remote.connection_",a,void 0);E9&&((0,g.F)(E9,function(b){b(a)}),E9.length=0);
b&&!a?g.KG("yt-remote-connection-change",!1):!b&&a&&g.KG("yt-remote-connection-change",!0)},Gua=function(){return g.u("yt.mdx.remote.connectData_")},G9=function(){var a=u9();
if(!a)return null;var b=w9().Sd();return g.NH(b,a)},Hua=function(a,b){z9(!0);
x9(!1);Bua(a,function(a){a?(yua(!0),g.JG("yt-remote-cast2-api-ready")):(A9("Failed to initialize cast API."),z9(!1),g.pH("yt-remote-cast-available"),g.pH("yt-remote-cast-receiver"),Cua());b(a)})},Iua=function(){return B9()?r9()?r9().getCastSession():(A9("getCastSelector: Cast is not initialized."),null):(A9("getCastSelector: Cast API is not installed!"),null)},Jua=function(){var a=Dua(),b=window.document.getElementById(a),c=b&&g.AF(b,"loaded");
c||b&&!c||(b=Eua(a,function(){g.AF(b,"loaded")||(g.BF(b,"loaded","true"),g.JG(a),g.TE(g.za(Fua,a),0))}))},Kua=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},Lua=function(){if(g.noa){var a=2,b=g.Eh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Jh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Gh,c)}},I9=function(a,b){u9();
G9()&&G9();Aua(a.id);var c=new g.SI(H9,a,D9());c.connect(b,Gua());c.subscribe("beforeDisconnect",function(a){g.KG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){s9()&&(s9(),F9(null))});
F9(c)},J9=function(){var a=g.TH();
if(!a)return null;var b=w9().Sd();return g.NH(b,a)},K9=function(a){g.BH("remote",a)},L9=function(){var a=s9();
return!!a&&3!=a.getProxyState()},M9=function(){y9()?r9().stopSession():A9("stopSession called before API ready.");
var a=s9();a&&(a.disconnect(1),F9(null))},Mua=function(){var a;
a=w9().Uc.$_gos();var b=G9();b&&s9()&&(g.MH(a,b)||a.push(b));return Kua(a)},O9=function(a,b){g.dG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.XB;this.A=this.o=null;this.H=(0,g.z)(this.DK,this);this.F=(0,g.z)(this.vk,this);this.G=(0,g.z)(this.CK,this);this.J=(0,g.z)(this.QK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Zs,this),Nua(this))):c=3;0!=c&&(b?this.Zs(c):g.TE((0,g.z)(function(){this.Zs(c)},this),0));
var d=Iua();d&&N9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},P9=function(a){return new g.HI(a.B.getPlayerContextData())},Oua=function(a,b,c,d,e){var f=P9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.LI(f,b,d);g.p(c)&&(g.JI(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);Q9(a,"setPlaylist",l);e||R9(a,f)},Nua=function(a){(0,g.F)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.MM,a),this))},a)},Pua=function(a){(0,g.F)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},S9=function(a,b){50>a.C.Dc()&&g.ZB(a.C,b)},T9=function(a,b,c){var d=P9(a);
g.JI(d,c);-1E3!=d.g&&(d.g=b);R9(a,d)},Q9=function(a,b,c){a.B.sendMessage(b,c)},R9=function(a,b){Pua(a);
a.B.setPlayerContextData(g.MI(b));Nua(a)},N9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.vk(null));
a.A=b;a.A&&(U9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.vk(a.A.media[0]))},Qua=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=P9(a);b.contentId!=d.videoId&&U9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.JI(d,a.o.getEstimatedTime());R9(a,d)}else U9("No cast media video. Ignoring state update.")},U9=function(a){g.BH("CP",a)},V9=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),Q9(this,b,c))},a)},Rua=function(a){var b=!1;
r9()||(a=new g.BI(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.nH("yt-remote-cast-available",a);g.KG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){q9("onReceiverSelected: "+a.friendlyName);
g.nH("yt-remote-cast-receiver",a);g.KG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){q9("onReceiverResumed: "+a.friendlyName);
g.nH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){q9("onSessionChange: "+g.JH(a));
a||g.pH("yt-remote-cast-receiver");g.KG("yt-remote-cast2-session-change",a)}),g.t("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
q9("cloudview.createSingleton_: "+b);return b},Sua=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.sG||a},W9=function(a,b){y9()?r9().setConnectedScreenStatus(a,b):A9("setConnectedScreenStatus called before ready.")},Tua=function(){q9("clearCurrentReceiver");
g.pH("yt-remote-cast-receiver")},Uua=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Lua();a({command:"cast.sender.init"});return}}if(window.chrome)if(Lua(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Ch();55<=b?a="55":50<=b&&(a="50");g.Jh("//www.gstatic.com/eureka/clank"+a+g.Hh,g.Gh)}else g.Kh(0);else g.Gh()},Vua=function(a){a?(g.nH("yt-remote-session-app",a.app),g.nH("yt-remote-session-name",a.name)):(g.pH("yt-remote-session-app"),g.pH("yt-remote-session-name"));
g.t("yt.mdx.remote.channelParams_",a,void 0)},Wua=function(){var a=D9();
if(g.Ub(a)){var a=g.SH(),b=g.oH("yt-remote-session-name")||"",c=g.oH("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.t("yt.mdx.remote.channelParams_",a,void 0)}},Xua=function(){var a=J9();
a?(K9("Resume connection to: "+g.JH(a)),I9(a,0)):(g.aI(),Tua(),K9("Skipping connecting because no session screen found."))},Yua=function(a){K9("remote.onCastSessionChange_: "+g.JH(a));
if(a){var b=G9();b&&b.id==a.id?W9(b.id,"YouTube TV"):(b&&M9(),I9(a,1))}else s9()&&M9()},Zua=function(){var a=Mua(),b=G9();
b||(b=J9());return g.ab(a,function(a){return b&&g.GH(b,a.key)?!0:!1})},$ua=function(){var a=g.oH("yt-remote-cast-receiver");
return a?a.friendlyName:null},ava=function(a,b,c,d){Sua()?Rua(b)&&(x9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Hua(a,c):(window.__onGCastApiAvailable=function(b,d){b?Hua(a,c):(A9("Failed to load cast API: "+d),z9(!1),x9(!1),g.pH("yt-remote-cast-available"),g.pH("yt-remote-cast-receiver"),Cua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Jua():Uua())):q9("Cannot initialize because not running Chrome")},
bva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.xg(a)||"";b&&(this.port=":"+b);this.A=g.wg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},X9=function(a){g.Y.call(this,{K:"div",
Y:"ytp-remote",R:[{K:"div",Y:"ytp-remote-display-status",R:[{K:"div",Y:"ytp-remote-display-status-icon",R:[g.pE()]},{K:"div",Y:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",Y:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.pR(this,250);g.M(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);cva(this,g.FK(a))},cva=function(a,b){if(3==a.A.Xa()){var c;
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR"):b.rb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING"):g.U("YTP_MDX_STATUS_CONNECTED");var d=a.A.Wc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.rR(a.g)},Y9=function(a,b,c){g.L.call(this);
this.H=a;this.X=b;b.addEventListener("onVolumeChange",this.tn,this);b.addEventListener("onCaptionsTrackListChanged",this.bz,this);b.addEventListener("captionschanged",this.Py,this);b.addEventListener("captionssettingschanged",this.ws,this);b.addEventListener("videoplayerreset",this.yk,this);b.addEventListener("mdxautoplaycancel",this.Pu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.pz,this);c.subscribe("remotePlayerChange",this.xk,this);c.subscribe("remoteQueueChange",this.yk,this);
c.subscribe("autoplayUpNext",this.Ny,this);c.subscribe("previousNextChange",this.mz,this);c.subscribe("nowAutoplaying",this.fz,this);c.subscribe("autoplayDismissed",this.My,this);this.suggestion=null;this.D=new g.VJ(64);this.o=new g.hu(this.BA,500,this);g.M(this,this.o);this.A=new g.hu(this.CA,1E3,this);g.M(this,this.A);this.B={};this.G=new g.hu(this.QA,1E3,this);g.M(this,this.G);this.F=new g.sk(this.QR,1E3,this);g.M(this,this.F);this.J=g.x;this.ws();this.yk();this.xk()},Z9=function(a,b){var c=a.H,
d=a.X.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},dva=function(a){Z9(a,0);
a.o.stop();$9(a,new g.VJ(64))},c$=function(a,b){if(a$(a)&&!a.C){var c=null;
b&&(c={style:a.X.Zk()},g.ac(c,b));a.g.vA(b$(a),c);a.B=P9(a.g).o}},d$=function(a,b){var c=a.X.bf();
c?Oua(a.g,b$(a),b,c.Qd(),c.listId.toString()):Oua(a.g,b$(a),b);$9(a,new g.VJ(1))},eva=function(a,b){if(b){var c=a.X.Wc("captions","tracklist",{ix:1});
c&&c.length?(a.X.De("captions","track",b),a.C=!1):(a.X.Vk("captions"),a.C=!0)}else a.X.De("captions","track",{})},a$=function(a){return P9(a.g).videoId==b$(a)},b$=function(a){return a.X.getVideoData().videoId},$9=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.V(b,2);if(d!=g.V(a.D,2)){var e=a.X;(e=g.EK(e.app,e.playerType||1))&&g.MT(e,d)}a.D=b;fva(a.H,c,b)}},e$=function(){var a=Zua();
!a&&B9()&&$ua()&&(a={key:"cast-selector-receiver",name:$ua()});return a},gva=function(){var a=Mua();
B9()&&g.oH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},hva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.lH&&xua();g.VH();H9||(H9=new bva,g.cI()&&(H9.g="/api/loungedev"));E9||(E9=g.u("yt.mdx.remote.deferredProxies_")||[],g.t("yt.mdx.remote.deferredProxies_",E9,void 0));Wua();var c=w9();if(!c){var d=new g.nI(H9);g.t("yt.mdx.remote.screenService_",d,void 0);c=w9();ava(a,d,function(a){a?u9()&&W9(u9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.KG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.t("yt.mdx.remote.initialized_",!0,void 0),K9("Initializing: "+g.Lc(b)),f$.push(g.GG("yt-remote-cast2-availability-change",function(){g.KG("yt-remote-receiver-availability-change")})),f$.push(g.GG("yt-remote-cast2-receiver-selected",function(){t9(null);
g.KG("yt-remote-auto-connect","cast-selector-receiver")})),f$.push(g.GG("yt-remote-cast2-receiver-resumed",function(){g.KG("yt-remote-receiver-resumed","cast-selector-receiver")})),f$.push(g.GG("yt-remote-cast2-session-change",Yua)),f$.push(g.GG("yt-remote-connection-change",function(a){a?W9(u9(),"YouTube TV"):J9()||(W9(null,null),Tua())})),a=D9(),b.isAuto&&(a.id+="#dial"),g.jG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,K9(" -- with channel params: "+g.Lc(a)),
Vua(a),c.start(),u9()||Xua())},g$=function(){B9()?r9()?y9()?(q9("Requesting cast selector."),r9().requestSession()):(q9("Wait for cast API to be ready to request the session."),C9.push(g.GG("yt-remote-cast2-api-ready",g$))):A9("requestCastSelector: Cast is not initialized."):A9("requestCastSelector: Cast API is not installed!")},h$=function(a){g.cR.call(this,a);
this.A={key:g.LH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.VJ(64);this.H=0;var b=g.xK(a).C;b&&(b=b.A&&b.A.g)&&(b=new o9(a,b),g.M(this,b));b=new X9(a);g.M(this,b);g.YK(a,b.element,5)},fva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.yS(c,b))},i$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)M9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.bf();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Wb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.mB(),0),currentTime:a.g.getCurrentTime()}}else c=null;K9("Connecting to: "+g.Lc(b));"cast-selector-receiver"==b.key?(t9(c||null),c=c||null,y9()?r9().setLaunchParams(c):A9("setLaunchParams called before ready.")):!c&&L9()&&u9()==b.key?g.KG("yt-remote-connection-change",
!0):(M9(),t9(c||null),c=w9().Sd(),(c=g.NH(c,b.key))&&I9(c,1))}};
g.ca(o9,g.FS);o9.prototype.H=function(){var a=this.X.Wc("remote","receivers");a&&1<a.length&&!this.X.Wc("remote","quickCast")?(this.G=g.Cb(a,this.F,this),g.HS(this,(0,g.H)(a,this.F)),a=this.X.Wc("remote","currentReceiver"),g.GS(this,this.F(a)),this.B||(g.n1(this.g,this),this.B=!0)):this.B&&(g.o1(this.g,this),this.B=!1)};
o9.prototype.F=function(a){return a.key};
o9.prototype.Me=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
o9.prototype.hd=function(a){g.FS.prototype.hd.call(this,a);this.X.De("remote","currentReceiver",this.G[a]);this.g.Tb()};
g.B(p9,g.OH);g.h=p9.prototype;g.h.Sd=function(a){return this.Uc.$_gs(a)};
g.h.contains=function(a){return!!this.Uc.$_c(a)};
g.h.get=function(a){return this.Uc.$_g(a)};
g.h.start=function(){this.Uc.$_st()};
g.h.po=function(a,b,c){this.Uc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Uc.$_r(a,b,c)};
g.h.ao=function(a,b,c,d){this.Uc.$_un(a,b,c,d)};
g.h.P=function(){for(var a=0,b=this.o.length;a<b;++a)this.Uc.$_ubk(this.o[a]);this.o.length=0;this.Uc=null;p9.O.P.call(this)};
g.h.VP=function(){this.U("screenChange")};
g.h.tM=function(){this.U("onlineScreenChange")};
var v9=null,C9=[],E9=null,H9=null;g.B(O9,g.dG);g.h=O9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,V9(this,"play")):Q9(this,"play"),T9(this,1,g.KI(P9(this))),this.U("remotePlayerChange")):S9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,V9(this,"pause")):Q9(this,"pause"),T9(this,2,g.KI(P9(this))),this.U("remotePlayerChange")):S9(this,this.pause)};
g.h.bB=function(a){if(1==this.g){if(this.o){var b=P9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,V9(this,"seekTo",{newTime:a}))}else Q9(this,"seekTo",{newTime:a});T9(this,3,a);this.U("remotePlayerChange")}else S9(this,g.za(this.bB,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,V9(this,"stopVideo")):Q9(this,"stopVideo");var a=P9(this);a.index=-1;a.videoId="";g.II(a);R9(this,a);this.U("remotePlayerChange")}else S9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=P9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){U9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){U9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Q9(this,"setVolume",e)}c.muted=b;c.volume=a;R9(this,c)}else S9(this,g.za(this.setVolume,a,b))};
g.h.vA=function(a,b){if(1==this.g){var c=P9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Lc(b.style),g.ac(d,c.o));Q9(this,"setSubtitlesTrack",d);R9(this,c)}else S9(this,g.za(this.vA,a,b))};
g.h.Ys=function(a,b){if(1==this.g){Q9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lc.id});var c=P9(this);c.audioTrackId=b.Lc.id;R9(this,c)}else S9(this,g.za(this.Ys,a,b))};
g.h.aB=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.LI(c,a,b);R9(this,c)}Q9(this,"previous")}else S9(this,g.za(this.aB,a,b))};
g.h.ZA=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.LI(c,a,b);R9(this,c)}Q9(this,"next")}else S9(this,g.za(this.ZA,a,b))};
g.h.Dv=function(){1==this.g?Q9(this,"dismissAutoplay"):S9(this,this.Dv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}O9.O.dispose.call(this)};
g.h.P=function(){Pua(this);this.B=null;this.C.clear();N9(this,null);O9.O.P.call(this)};
g.h.Zs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.$B(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.MM=function(a,b){this.U(a,b)};
g.h.DK=function(a){if(!a)this.vk(null),N9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=P9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)U9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,R9(this,b)}};
g.h.vk=function(a){U9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Qua(this),this.U("remotePlayerChange")};
g.h.CK=function(a){a?(Qua(this),this.U("remotePlayerChange")):this.vk(null)};
g.h.QK=function(){var a=Iua();a&&N9(this,a)};
g.h.Zb=function(a){g.BH("CP",a)};
var f$=[];g.h=bva.prototype;g.h.Ch=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Fg(d+a,b||{})};
g.h.Xs=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.za(this.QP,c,!0),onError:g.za(this.PP,d),gd:g.za(this.RP,d)};b&&(c.Nb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.fF(a,c)};
g.h.QP=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.PP=function(a,b){a(Error("Request error: "+b.status))};
g.h.RP=function(a){a(Error("request timed out"))};
g.ca(X9,g.Y);X9.prototype.B=function(a){cva(this,a.state)};
g.B(Y9,g.L);g.h=Y9.prototype;
g.h.P=function(){Y9.O.P.call(this);this.o.stop();this.A.stop();this.J();this.X.removeEventListener("onVolumeChange",this.tn,this);this.X.removeEventListener("onCaptionsTrackListChanged",this.bz,this);this.X.removeEventListener("captionschanged",this.Py,this);this.X.removeEventListener("videoplayerreset",this.yk,this);this.X.removeEventListener("captionssettingschanged",this.ws,this);this.X.removeEventListener("mdxautoplaycancel",this.Pu,this);this.g.unsubscribe("proxyStateChange",this.pz,this);this.g.unsubscribe("remotePlayerChange",
this.xk,this);this.g.unsubscribe("remoteQueueChange",this.yk,this);this.g.unsubscribe("autoplayUpNext",this.Ny,this);this.g.unsubscribe("previousNextChange",this.mz,this);this.g.unsubscribe("nowAutoplaying",this.fz,this);this.g.unsubscribe("autoplayDismissed",this.My,this);this.g=this.H=null};
g.h.PB=function(a,b){2==this.g.g||(a$(this)?this.uG.apply(this,arguments):this.qG.apply(this,arguments))};
g.h.Py=function(a){this.PB("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.ws=function(){var a=this.X.Wc("captions","track");g.Ub(a)||c$(this,a)};
g.h.qG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":d$(this,this.X.getCurrentTime());break;case "control_seek":d$(this,c[0]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.Ys(b$(this),c)}};
g.h.uG=function(a,b){if(1081!=P9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":P9(this.g).rb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Ji(c[0],c[1]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.Ys(b$(this),c)}}};
g.h.tn=function(a){if(a$(this)){this.g.unsubscribe("remotePlayerChange",this.xk,this);var b=Math.round(a.volume);a=!!a.muted;var c=P9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.xk,this)}};
g.h.bz=function(){g.Ub(this.B)||eva(this,this.B);this.C=!1};
g.h.pz=function(a,b){this.A.stop();2==b&&this.CA()};
g.h.xk=function(){if(a$(this)){this.o.stop();var a=P9(this.g);switch(a.g){case 1081:$9(this,new g.VJ(8));break;case 1:this.BA();$9(this,new g.VJ(8));break;case 1083:case 3:$9(this,new g.VJ(9));break;case 0:$9(this,new g.VJ(2));this.F.stop();Z9(this,this.X.getVideoData().lengthSeconds);break;case 1082:$9(this,new g.VJ(4));break;case 2:$9(this,new g.VJ(4));Z9(this,g.KI(a));break;case -1:$9(this,new g.VJ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},$9(this,
new g.VJ(128,a))}var a=P9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,eva(this,a));a=P9(this.g);-1==a.volume||Math.round(this.X.getVolume())==a.volume&&this.X.Yd()==a.muted||this.G.isActive()||this.QA()}else dva(this)};
g.h.mz=function(){this.X.U("mdxpreviousnextchange")};
g.h.yk=function(){a$(this)||dva(this)};
g.h.Pu=function(){this.g.Dv()};
g.h.Ny=function(a){a&&(a=g.fF("/watch_queue_ajax",{method:"GET",Hc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.z)(this.KN,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.KN=function(a,b){var c=new g.xQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.X.U("mdxautoplayupnext",c)};
g.h.fz=function(a){(0,window.isNaN)(a)||this.X.U("mdxnowautoplaying",a)};
g.h.My=function(){this.X.U("mdxautoplaycanceled")};
g.h.QR=function(a,b){-1==P9(this.g).g?d$(this,a):b&&this.g.bB(a)};
g.h.QA=function(){if(a$(this)){var a=P9(this.g);this.X.removeEventListener("onVolumeChange",this.tn,this);a.muted?this.X.mute():this.X.vg();this.X.setVolume(a.volume);this.X.addEventListener("onVolumeChange",this.tn,this)}};
g.h.BA=function(){this.o.stop();if(!this.g.la()){var a=P9(this.g);a.rb()&&$9(this,new g.VJ(8));Z9(this,g.KI(a));this.o.start()}};
g.h.CA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.B(h$,g.cR);g.h=h$.prototype;g.h.create=function(){hva("embedded"==g.X(this.g).g);this.D.push(g.GG("yt-remote-before-disconnect",this.zK,this));this.D.push(g.GG("yt-remote-connection-change",this.VM,this));this.D.push(g.GG("yt-remote-receiver-availability-change",this.nz,this));this.D.push(g.GG("yt-remote-auto-connect",this.TM,this));this.D.push(g.GG("yt-remote-receiver-resumed",this.SM,this));this.nz()};
g.h.load=function(){this.g.Ap();h$.O.load.call(this);this.C=new Y9(this,this.g,this.o);var a;a=(a=Gua())?a.currentTime:0;var b=L9()?new O9(s9(),void 0):null;0==a&&b&&(a=g.KI(P9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));fva(this,this.F,this.F);g.t2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Ue(this.C,this.o);this.o=this.C=null;h$.O.unload.call(this);g.t2(this.g.app,5)};
g.h.P=function(){g.HG(this.D);h$.O.P.call(this)};
g.h.fl=function(a,b){this.loaded&&this.C.PB.apply(this.C,arguments)};
g.h.VF=function(){return this.loaded?this.C.suggestion:null};
g.h.zf=function(){return this.o?P9(this.o).zf:!1};
g.h.hasNext=function(){return this.o?P9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.uR=function(){var a=P9(this.o),b=this.g.getVideoData(),c=this.g.Fd(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.E)()-a.A)/1E3:a.B;var l=1>=wua(a)-this.getCurrentTime(),m=a.J,n=wua(a),a=0<a.C?a.C+((0,g.E)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.vR=function(){this.o&&this.o.ZA()};
g.h.wR=function(){this.o&&this.o.aB()};
g.h.zK=function(a){1==a&&(this.J=this.o?P9(this.o):null)};
g.h.VM=function(){var a=L9()?new O9(s9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Te(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Qc(g.KI(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.nz=function(){this.G=[this.A].concat(gva());var a=e$()||this.A;i$(this,a);this.g.xa("onMdxReceiversChange")};
g.h.TM=function(){var a=e$();i$(this,a)};
g.h.SM=function(){this.B=e$()};
g.h.tR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?g$():i$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&g$(),!0):!1}};
g.h.xR=function(){Q9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.xe=function(){return!1};
window._exportCheck==g.Ba&&g.t("ytmod.player.remote",h$,void 0);})(_yt_player);
