(function(g){var window=this;var Aua=function(a,b){var c=[];g.dm(b,function(a){var b;try{b=g.hI.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.KF(b)&&c.push(a):c.push(a)},a);
return c},Bua=function(a,b){var c=Aua(a,b);
(0,g.K)(c,function(a){g.hI.prototype.remove.call(this,a)},a)},Cua=function(){var a=g.MK;
Bua(a,a.g.Gd(!0))},Dua=function(a){return a.H?a.F+((0,g.C)()-a.A)/1E3:a.F},v9=function(a){g.Si("cloudview",a)},w9=function(a){g.zu.call(this,"ScreenServiceProxy");
this.Qc=a;this.o=[];this.o.push(this.Qc.$_s("screenChange",(0,g.z)(this.JO,this)));this.o.push(this.Qc.$_s("onlineScreenChange",(0,g.z)(this.dL,this)))},Eua=function(a){v9("setApiReady_ "+a);
g.oa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},x9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},Fua=function(a){g.xs[a]&&(a=g.xs[a],(0,g.K)(a,function(a){g.vs[a]&&delete g.vs[a]}),a.length=0)},y9=function(){return g.u("yt.mdx.remote.connection_")},z9=function(a){g.oa("yt.mdx.remote.connectData_",a,void 0)},Gua=function(a){g.oa("yt.mdx.remote.currentScreenId_",a,void 0)},A9=function(){return g.u("yt.mdx.remote.currentScreenId_")},C9=function(){if(!B9){var a=g.u("yt.mdx.remote.screenService_");
B9=a?new w9(a):null}return B9},D9=function(a){g.oa("yt.mdx.remote.cloudview.initializing_",a,void 0)},E9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},F9=function(a){v9("setCastInstalled_ "+a);
g.OK("yt-remote-cast-installed",a)},G9=function(a){g.Si("cloudview",a)},Hua=function(a,b){x9().init(a,b)},H9=function(){return!!g.PK("yt-remote-cast-installed")},Iua=function(){v9("dispose");
var a=x9();a&&a.dispose();g.oa("yt.mdx.remote.cloudview.instance_",null,void 0);Eua(!1);g.zs(I9);I9.length=0},Jua=function(){var a=window.document.createElement("a");
g.vo(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.dc(a)},Kua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Lua=function(a){var b=g.ts();
if(b)if(b.clear(a),a)Fua(a);else for(var c in g.xs)Fua(c)},J9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},L9=function(a){var b=y9();
z9(null);a||Gua("");g.oa("yt.mdx.remote.connection_",a,void 0);K9&&((0,g.K)(K9,function(b){b(a)}),K9.length=0);
b&&!a?g.Cs("yt-remote-connection-change",!1):!b&&a&&g.Cs("yt-remote-connection-change",!0)},Mua=function(){return g.u("yt.mdx.remote.connectData_")},M9=function(){var a=A9();
if(!a)return null;var b=C9().Ld();return g.Em(b,a)},Nua=function(a,b){F9(!0);
D9(!1);Hua(a,function(a){a?(Eua(!0),g.Bs("yt-remote-cast2-api-ready")):(G9("Failed to initialize cast API."),F9(!1),g.QK("yt-remote-cast-available"),g.QK("yt-remote-cast-receiver"),Iua());b(a)})},Oua=function(){return H9()?x9()?x9().getCastSession():(G9("getCastSelector: Cast is not initialized."),null):(G9("getCastSelector: Cast API is not installed!"),null)},Pua=function(){var a=Jua(),b=window.document.getElementById(a),c=b&&g.yc(b,"loaded");
c||b&&!c||(b=Kua(a,function(){g.yc(b,"loaded")||(g.zc(b,"loaded","true"),g.Bs(a),g.yk(g.za(Lua,a),0))}))},Qua=function(a){return(0,g.M)(a,function(a){return{key:a.id,
name:a.name}})},Rua=function(){if(g.koa){var a=2,b=g.Ea(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Ja("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ga,c)}},O9=function(a,b){A9();
M9()&&M9();Gua(a.id);var c=new g.xY(N9,a,J9());c.connect(b,Mua());c.subscribe("beforeDisconnect",function(a){g.Cs("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y9()&&(y9(),L9(null))});
L9(c)},P9=function(){var a=g.QL();
if(!a)return null;var b=C9().Ld();return g.Em(b,a)},Q9=function(a){g.Si("remote",a)},R9=function(){var a=y9();
return!!a&&3!=a.getProxyState()},S9=function(){E9()?x9().stopSession():G9("stopSession called before API ready.");
var a=y9();a&&(a.disconnect(1),L9(null))},Sua=function(){var a;
a=C9().Qc.$_gos();var b=M9();b&&y9()&&(g.Dm(a,b)||a.push(b));return Qua(a)},U9=function(a,b){g.rs.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.Zh;this.A=this.o=null;this.H=(0,g.z)(this.qJ,this);this.F=(0,g.z)(this.ck,this);this.G=(0,g.z)(this.pJ,this);this.J=(0,g.z)(this.DJ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.xs,this),Tua(this))):c=3;0!=c&&(b?this.xs(c):g.yk((0,g.z)(function(){this.xs(c)},this),0));
var d=Oua();d&&T9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},V9=function(a){return new g.$d(a.B.getPlayerContextData())},Uua=function(a,b,c,d,e){var f=V9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.de(f,b,d);g.p(c)&&(g.be(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);W9(a,"setPlaylist",l);e||X9(a,f)},Tua=function(a){(0,g.K)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.wL,a),this))},a)},Vua=function(a){(0,g.K)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Y9=function(a,b){50>a.C.zc()&&g.ai(a.C,b)},Z9=function(a,b,c){var d=V9(a);
g.be(d,c);-1E3!=d.g&&(d.g=b);X9(a,d)},W9=function(a,b,c){a.B.sendMessage(b,c)},X9=function(a,b){Vua(a);
a.B.setPlayerContextData(g.ee(b));Tua(a)},T9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.ck(null));
a.A=b;a.A&&($9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.ck(a.A.media[0]))},Wua=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=V9(a);b.contentId!=d.videoId&&$9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.be(d,a.o.getEstimatedTime());X9(a,d)}else $9("No cast media video. Ignoring state update.")},$9=function(a){g.Si("CP",a)},a$=function(a,b,c){return(0,g.z)(function(a){this.Vb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Vb("Retrying "+b+" using MDx browser channel."),W9(this,b,c))},a)},Xua=function(a){var b=!1;
x9()||(a=new g.OT(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.OK("yt-remote-cast-available",a);g.Cs("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){v9("onReceiverSelected: "+a.friendlyName);
g.OK("yt-remote-cast-receiver",a);g.Cs("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){v9("onReceiverResumed: "+a.friendlyName);
g.OK("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){v9("onSessionChange: "+g.$i(a));
a||g.QK("yt-remote-cast-receiver");g.Cs("yt-remote-cast2-session-change",a)}),g.oa("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
v9("cloudview.createSingleton_: "+b);return b},Yua=function(){var a=0<=g.Id.search(/\ (CrMo|Chrome|CriOS)\//);
return g.Sp||a},b$=function(a,b){E9()?x9().setConnectedScreenStatus(a,b):G9("setConnectedScreenStatus called before ready.")},Zua=function(){v9("clearCurrentReceiver");
g.QK("yt-remote-cast-receiver")},$ua=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Rua();a({command:"cast.sender.init"});return}}if(window.chrome&&window.isSecureContext)if(Rua(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Ca();55<=b?a="55":50<=b&&(a="50");g.Ja("//www.gstatic.com/eureka/clank"+a+g.Ha,g.Ga)}else g.Ka(0);else g.Ga()},ava=function(a){a?(g.OK("yt-remote-session-app",a.app),g.OK("yt-remote-session-name",a.name)):(g.QK("yt-remote-session-app"),g.QK("yt-remote-session-name"));
g.oa("yt.mdx.remote.channelParams_",a,void 0)},bva=function(){var a=J9();
if(g.Bb(a)){var a=g.PL(),b=g.PK("yt-remote-session-name")||"",c=g.PK("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.oa("yt.mdx.remote.channelParams_",a,void 0)}},cva=function(){var a=P9();
a?(Q9("Resume connection to: "+g.$i(a)),O9(a,0)):(g.YL(),Zua(),Q9("Skipping connecting because no session screen found."))},dva=function(a){Q9("remote.onCastSessionChange_: "+g.$i(a));
if(a){var b=M9();b&&b.id==a.id?b$(b.id,"YouTube TV"):(b&&S9(),O9(a,1))}else y9()&&S9()},eva=function(){var a=Sua(),b=M9();
b||(b=P9());return g.ye(a,function(a){return b&&g.Xi(b,a.key)?!0:!1})},fva=function(){var a=g.PK("yt-remote-cast-receiver");
return a?a.friendlyName:null},gva=function(a,b,c,d){Yua()?Xua(b)&&(D9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Nua(a,c):(window.__onGCastApiAvailable=function(b,d){b?Nua(a,c):(G9("Failed to load cast API: "+d),F9(!1),D9(!1),g.QK("yt-remote-cast-available"),g.QK("yt-remote-cast-receiver"),Iua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Pua():$ua())):v9("Cannot initialize because not running Chrome")},
hva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.yf(a)||"";b&&(this.port=":"+b);this.A=g.xf(a)||"";a=g.Id;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.cc(a,"10.0")&&(this.o=!1))},c$=function(){var a=eva();
!a&&H9()&&fva()&&(a={key:"cast-selector-receiver",name:fva()});return a},iva=function(){var a=Sua();
H9()&&g.PK("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},jva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.MK&&Cua();g.SL();N9||(N9=new hva,g.$L()&&(N9.g="/api/loungedev"));K9||(K9=g.u("yt.mdx.remote.deferredProxies_")||[],g.oa("yt.mdx.remote.deferredProxies_",K9,void 0));bva();var c=C9();if(!c){var d=new g.WO(N9);g.oa("yt.mdx.remote.screenService_",d,void 0);c=C9();gva(a,d,function(a){a?A9()&&b$(A9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.Cs("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.oa("yt.mdx.remote.initialized_",!0,void 0),Q9("Initializing: "+g.Az(b)),d$.push(g.ys("yt-remote-cast2-availability-change",function(){g.Cs("yt-remote-receiver-availability-change")})),d$.push(g.ys("yt-remote-cast2-receiver-selected",function(){z9(null);
g.Cs("yt-remote-auto-connect","cast-selector-receiver")})),d$.push(g.ys("yt-remote-cast2-receiver-resumed",function(){g.Cs("yt-remote-receiver-resumed","cast-selector-receiver")})),d$.push(g.ys("yt-remote-cast2-session-change",dva)),d$.push(g.ys("yt-remote-connection-change",function(a){a?b$(A9(),"YouTube TV"):P9()||(b$(null,null),Zua())})),a=J9(),b.isAuto&&(a.id+="#dial"),g.Tf("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,Q9(" -- with channel params: "+g.Az(a)),
ava(a),c.start(),A9()||cva())},e$=function(a,b,c){g.H.call(this);
this.H=a;this.Y=b;b.addEventListener("onVolumeChange",this.Um,this);b.addEventListener("onCaptionsTrackListChanged",this.Wx,this);b.addEventListener("captionschanged",this.Kx,this);b.addEventListener("captionssettingschanged",this.Jr,this);b.addEventListener("videoplayerreset",this.fk,this);b.addEventListener("mdxautoplaycancel",this.mu,this);this.C=!1;this.g=c;c.isDisposed();c.subscribe("proxyStateChange",this.ky,this);c.subscribe("remotePlayerChange",this.ek,this);c.subscribe("remoteQueueChange",
this.fk,this);c.subscribe("autoplayUpNext",this.Ix,this);c.subscribe("previousNextChange",this.hy,this);c.subscribe("nowAutoplaying",this.Zx,this);c.subscribe("autoplayDismissed",this.Hx,this);this.suggestion=null;this.D=new g.dG(64);this.o=new g.qz(this.Cz,500,this);g.J(this,this.o);this.A=new g.qz(this.Dz,1E3,this);g.J(this,this.A);this.B={};this.G=new g.qz(this.Rz,1E3,this);g.J(this,this.G);this.F=new g.tz(this.DQ,1E3,this);g.J(this,this.F);this.J=g.x;this.Jr();this.fk();this.ek()},f$=function(a,
b){var c=a.H,d=a.Y.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},kva=function(a){f$(a,0);
a.o.stop();g$(a,new g.dG(64))},j$=function(a,b){if(h$(a)&&!a.C){var c=null;
b&&(c={style:a.Y.Gk()},g.Hb(c,b));a.g.vz(i$(a),c);a.B=V9(a.g).o}},k$=function(a,b){var c=a.Y.Ue();
c?Uua(a.g,i$(a),b,c.Jd(),c.listId.toString()):Uua(a.g,i$(a),b);g$(a,new g.dG(1))},lva=function(a,b){if(b){var c=a.Y.Sc("captions","tracklist",{zw:1});
c&&c.length?(a.Y.ue("captions","track",b),a.C=!1):(a.Y.Ck("captions"),a.C=!0)}else a.Y.ue("captions","track",{})},h$=function(a){return V9(a.g).videoId==i$(a)},i$=function(a){return a.Y.getVideoData().videoId},g$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.G(b,2);if(d!=g.G(a.D,2)){var e=a.Y;(e=g.LS(e.app,e.playerType||1))&&g.OV(e,d)}a.D=b;mva(a.H,c,b)}},l$=function(){H9()?x9()?E9()?(v9("Requesting cast selector."),x9().requestSession()):(v9("Wait for cast API to be ready to request the session."),I9.push(g.ys("yt-remote-cast2-api-ready",l$))):G9("requestCastSelector: Cast is not initialized."):G9("requestCastSelector: Cast API is not installed!")},m$=function(a){g.fv.call(this,a);
this.A={key:g.Cm(),name:g.L("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.dG(64);this.H=0},mva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.$c(c,b))},n$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)S9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.Ue();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Tb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.qA(),0),currentTime:a.g.getCurrentTime()}}else c=null;Q9("Connecting to: "+g.Az(b));"cast-selector-receiver"==b.key?(z9(c||null),c=c||null,E9()?x9().setLaunchParams(c):G9("setLaunchParams called before ready.")):!c&&R9()&&A9()==b.key?g.Cs("yt-remote-connection-change",
!0):(S9(),z9(c||null),c=C9().Ld(),(c=g.Em(c,b.key))&&O9(c,1))}};
g.B(w9,g.zu);g.h=w9.prototype;g.h.Ld=function(a){return this.Qc.$_gs(a)};
g.h.contains=function(a){return!!this.Qc.$_c(a)};
g.h.get=function(a){return this.Qc.$_g(a)};
g.h.start=function(){this.Qc.$_st()};
g.h.Sn=function(a,b,c){this.Qc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Qc.$_r(a,b,c)};
g.h.Gn=function(a,b,c,d){this.Qc.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.o.length;a<b;++a)this.Qc.$_ubk(this.o[a]);this.o.length=0;this.Qc=null;w9.N.R.call(this)};
g.h.JO=function(){this.U("screenChange")};
g.h.dL=function(){this.U("onlineScreenChange")};
var B9=null,I9=[],K9=null,N9=null;g.B(U9,g.rs);g.h=U9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,a$(this,"play")):W9(this,"play"),Z9(this,1,g.ce(V9(this))),this.U("remotePlayerChange")):Y9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,a$(this,"pause")):W9(this,"pause"),Z9(this,2,g.ce(V9(this))),this.U("remotePlayerChange")):Y9(this,this.pause)};
g.h.fA=function(a){if(1==this.g){if(this.o){var b=V9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.jb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,a$(this,"seekTo",{newTime:a}))}else W9(this,"seekTo",{newTime:a});Z9(this,3,a);this.U("remotePlayerChange")}else Y9(this,g.za(this.fA,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,a$(this,"stopVideo")):W9(this,"stopVideo");var a=V9(this);a.index=-1;a.videoId="";g.ae(a);X9(this,a);this.U("remotePlayerChange")}else Y9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=V9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){$9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Vb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){$9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Vb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W9(this,"setVolume",e)}c.muted=b;c.volume=a;X9(this,c)}else Y9(this,g.za(this.setVolume,a,b))};
g.h.vz=function(a,b){if(1==this.g){var c=V9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Az(b.style),g.Hb(d,c.o));W9(this,"setSubtitlesTrack",d);X9(this,c)}else Y9(this,g.za(this.vz,a,b))};
g.h.ws=function(a,b){if(1==this.g){W9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Hc.id});var c=V9(this);c.audioTrackId=b.Hc.id;X9(this,c)}else Y9(this,g.za(this.ws,a,b))};
g.h.eA=function(a,b){if(1==this.g){if(a&&b){var c=V9(this);g.de(c,a,b);X9(this,c)}W9(this,"previous")}else Y9(this,g.za(this.eA,a,b))};
g.h.dA=function(a,b){if(1==this.g){if(a&&b){var c=V9(this);g.de(c,a,b);X9(this,c)}W9(this,"next")}else Y9(this,g.za(this.dA,a,b))};
g.h.Vu=function(){1==this.g?W9(this,"dismissAutoplay"):Y9(this,this.Vu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}U9.N.dispose.call(this)};
g.h.R=function(){Vua(this);this.B=null;this.C.clear();T9(this,null);U9.N.R.call(this)};
g.h.xs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.bi(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.wL=function(a,b){this.U(a,b)};
g.h.qJ=function(a){if(!a)this.ck(null),T9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=V9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)$9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,X9(this,b)}};
g.h.ck=function(a){$9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Wua(this),this.U("remotePlayerChange")};
g.h.pJ=function(a){a?(Wua(this),this.U("remotePlayerChange")):this.ck(null)};
g.h.DJ=function(){var a=Oua();a&&T9(this,a)};
g.h.Vb=function(a){g.Si("CP",a)};
var d$=[];g.h=hva.prototype;g.h.sh=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Gf(d+a,b||{})};
g.h.us=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Gb:g.za(this.EO,c,!0),onError:g.za(this.DO,d),ad:g.za(this.FO,d)};b&&(c.Mb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.yB(a,c)};
g.h.EO=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.DO=function(a,b){a(Error("Request error: "+b.status))};
g.h.FO=function(a){a(Error("request timed out"))};
g.B(e$,g.H);g.h=e$.prototype;
g.h.R=function(){e$.N.R.call(this);this.o.stop();this.A.stop();this.J();this.Y.removeEventListener("onVolumeChange",this.Um,this);this.Y.removeEventListener("onCaptionsTrackListChanged",this.Wx,this);this.Y.removeEventListener("captionschanged",this.Kx,this);this.Y.removeEventListener("videoplayerreset",this.fk,this);this.Y.removeEventListener("captionssettingschanged",this.Jr,this);this.Y.removeEventListener("mdxautoplaycancel",this.mu,this);this.g.unsubscribe("proxyStateChange",this.ky,this);this.g.unsubscribe("remotePlayerChange",
this.ek,this);this.g.unsubscribe("remoteQueueChange",this.fk,this);this.g.unsubscribe("autoplayUpNext",this.Ix,this);this.g.unsubscribe("previousNextChange",this.hy,this);this.g.unsubscribe("nowAutoplaying",this.Zx,this);this.g.unsubscribe("autoplayDismissed",this.Hx,this);this.g=this.H=null};
g.h.XA=function(a,b){2==this.g.g||(h$(this)?this.LF.apply(this,arguments):this.HF.apply(this,arguments))};
g.h.Kx=function(a){this.XA("control_subtitles_set_track",g.Bb(a)?null:a)};
g.h.Jr=function(){var a=this.Y.Sc("captions","track");g.Bb(a)||j$(this,a)};
g.h.HF=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":k$(this,this.Y.getCurrentTime());break;case "control_seek":k$(this,c[0]);break;case "control_subtitles_set_track":j$(this,c[0]);break;case "control_set_audio_track":c=c[0],h$(this)&&this.g.ws(i$(this),c)}};
g.h.LF=function(a,b){if(1081!=V9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":V9(this.g).jb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.si(c[0],c[1]);break;case "control_subtitles_set_track":j$(this,c[0]);break;case "control_set_audio_track":c=c[0],h$(this)&&this.g.ws(i$(this),c)}}};
g.h.Um=function(a){if(h$(this)){this.g.unsubscribe("remotePlayerChange",this.ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=V9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.ek,this)}};
g.h.Wx=function(){g.Bb(this.B)||lva(this,this.B);this.C=!1};
g.h.ky=function(a,b){this.A.stop();2==b&&this.Dz()};
g.h.ek=function(){if(h$(this)){this.o.stop();var a=V9(this.g);switch(a.g){case 1081:g$(this,new g.dG(8));break;case 1:this.Cz();g$(this,new g.dG(8));break;case 1083:case 3:g$(this,new g.dG(9));break;case 0:g$(this,new g.dG(2));this.F.stop();f$(this,this.Y.getVideoData().lengthSeconds);break;case 1082:g$(this,new g.dG(4));break;case 2:g$(this,new g.dG(4));f$(this,g.ce(a));break;case -1:g$(this,new g.dG(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.L("YTP_MDX_PLAYER_ERROR")},g$(this,
new g.dG(128,a))}var a=V9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,lva(this,a));a=V9(this.g);-1==a.volume||Math.round(this.Y.getVolume())==a.volume&&this.Y.Td()==a.muted||this.G.isActive()||this.Rz()}else kva(this)};
g.h.hy=function(){this.Y.U("mdxpreviousnextchange")};
g.h.fk=function(){h$(this)||kva(this)};
g.h.mu=function(){this.g.Vu()};
g.h.Ix=function(a){a&&(a=g.yB("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},Gb:(0,g.z)(this.uM,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.uM=function(a,b){var c=new g.kU({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.Y.U("mdxautoplayupnext",c)};
g.h.Zx=function(a){(0,window.isNaN)(a)||this.Y.U("mdxnowautoplaying",a)};
g.h.Hx=function(){this.Y.U("mdxautoplaycanceled")};
g.h.DQ=function(a,b){-1==V9(this.g).g?k$(this,a):b&&this.g.fA(a)};
g.h.Rz=function(){if(h$(this)){var a=V9(this.g);this.Y.removeEventListener("onVolumeChange",this.Um,this);a.muted?this.Y.mute():this.Y.kg();this.Y.setVolume(a.volume);this.Y.addEventListener("onVolumeChange",this.Um,this)}};
g.h.Cz=function(){this.o.stop();if(!this.g.isDisposed()){var a=V9(this.g);a.jb()&&g$(this,new g.dG(8));f$(this,g.ce(a));this.o.start()}};
g.h.Dz=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.B(m$,g.fv);g.h=m$.prototype;g.h.create=function(){jva("embedded"==g.X(this.g).g);this.D.push(g.ys("yt-remote-before-disconnect",this.mJ,this));this.D.push(g.ys("yt-remote-connection-change",this.GL,this));this.D.push(g.ys("yt-remote-receiver-availability-change",this.iy,this));this.D.push(g.ys("yt-remote-auto-connect",this.DL,this));this.D.push(g.ys("yt-remote-receiver-resumed",this.CL,this));this.iy()};
g.h.load=function(){this.g.bp();m$.N.load.call(this);this.C=new e$(this,this.g,this.o);var a;a=(a=Mua())?a.currentTime:0;var b=R9()?new U9(y9(),void 0):null;0==a&&b&&(a=g.ce(V9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));mva(this,this.F,this.F);g.A2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Fd(this.C,this.o);this.o=this.C=null;m$.N.unload.call(this);g.A2(this.g.app,5)};
g.h.R=function(){g.zs(this.D);m$.N.R.call(this)};
g.h.Kk=function(a,b){this.loaded&&this.C.XA.apply(this.C,arguments)};
g.h.mF=function(){return this.loaded?this.C.suggestion:null};
g.h.qf=function(){return this.o?V9(this.o).qf:!1};
g.h.hasNext=function(){return this.o?V9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.iQ=function(){var a=V9(this.o),b=this.g.getVideoData(),c=this.g.Ah(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.C)()-a.A)/1E3:a.B;var l=1>=Dua(a)-this.getCurrentTime(),m=a.J,n=Dua(a),a=0<a.C?a.C+((0,g.C)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.jQ=function(){this.o&&this.o.dA()};
g.h.kQ=function(){this.o&&this.o.eA()};
g.h.mJ=function(a){1==a&&(this.J=this.o?V9(this.o):null)};
g.h.GL=function(){var a=R9()?new U9(y9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ed(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Mc(g.ce(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.iy=function(){this.G=[this.A].concat(iva());var a=c$()||this.A;n$(this,a);this.g.va("onMdxReceiversChange")};
g.h.DL=function(){var a=c$();n$(this,a)};
g.h.CL=function(){this.B=c$()};
g.h.hQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l$():n$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&l$(),!0):!1}};
g.h.lQ=function(){W9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.oe=function(){return!1};
window._exportCheck==g.Ba&&g.oa("ytmod.player.remote",m$,void 0);})(_yt_player);
