(function(g){var window=this;var Pua=function(a,b){var c=[];g.om(b,function(a){var b;try{b=g.XD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.WD(b)&&c.push(a):c.push(a)},a);
return c},Qua=function(a,b){var c=Pua(a,b);
(0,g.H)(c,function(a){g.XD.prototype.remove.call(this,a)},a)},o9=function(a,b){g.yW.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.W=a;this.B=!1;this.G={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},Rua=function(a){return a.H?a.F+((0,g.F)()-a.A)/1E3:a.F},Sua=function(){var a=g.yH;
Qua(a,a.g.Nd(!0))},p9=function(a){g.aI.call(this,"ScreenServiceProxy");
this.Uc=a;this.o=[];this.o.push(this.Uc.$_s("screenChange",(0,g.A)(this.dQ,this)));this.o.push(this.Uc.$_s("onlineScreenChange",(0,g.A)(this.yM,this)))},q9=function(a){g.OH("cloudview",a)},Tua=function(a){q9("setApiReady_ "+a);
g.u("yt.mdx.remote.cloudview.apiReady_",a,void 0)},r9=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Uua=function(a){g.SG[a]&&(a=g.SG[a],(0,g.H)(a,function(a){g.QG[a]&&delete g.QG[a]}),a.length=0)},s9=function(){return g.x("yt.mdx.remote.connection_")},t9=function(a){g.u("yt.mdx.remote.connectData_",a,void 0)},Vua=function(a){g.u("yt.mdx.remote.currentScreenId_",a,void 0)},u9=function(){return g.x("yt.mdx.remote.currentScreenId_")},w9=function(){if(!v9){var a=g.x("yt.mdx.remote.screenService_");
v9=a?new p9(a):null}return v9},x9=function(a){g.u("yt.mdx.remote.cloudview.initializing_",a,void 0)},y9=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},z9=function(a){q9("setCastInstalled_ "+a);
g.AH("yt-remote-cast-installed",a)},A9=function(a){g.OH("cloudview",a)},Wua=function(a,b){r9().init(a,b)},B9=function(){return!!g.BH("yt-remote-cast-installed")},Xua=function(){q9("dispose");
var a=r9();a&&a.dispose();g.u("yt.mdx.remote.cloudview.instance_",null,void 0);Tua(!1);(0,g.l2)(C9);C9.length=0},Yua=function(){var a=window.document.createElement("a");
g.Qd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Sa(a)},Zua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},$ua=function(a){var b=g.PG();
if(b)if(b.clear(a),a)Uua(a);else for(var c in g.SG)Uua(c)},D9=function(){return g.x("yt.mdx.remote.channelParams_")||{}},F9=function(a){var b=s9();
t9(null);a||Vua("");g.u("yt.mdx.remote.connection_",a,void 0);E9&&((0,g.H)(E9,function(b){b(a)}),E9.length=0);
b&&!a?g.XG("yt-remote-connection-change",!1):!b&&a&&g.XG("yt-remote-connection-change",!0)},ava=function(){return g.x("yt.mdx.remote.connectData_")},G9=function(){var a=u9();
if(!a)return null;var b=w9().Sd();return g.$H(b,a)},bva=function(a,b){z9(!0);
x9(!1);Wua(a,function(a){a?(Tua(!0),g.WG("yt-remote-cast2-api-ready")):(A9("Failed to initialize cast API."),z9(!1),g.CH("yt-remote-cast-available"),g.CH("yt-remote-cast-receiver"),Xua());b(a)})},cva=function(){return B9()?r9()?r9().getCastSession():(A9("getCastSelector: Cast is not initialized."),null):(A9("getCastSelector: Cast API is not installed!"),null)},dva=function(){var a=Yua(),b=window.document.getElementById(a),c=b&&g.OF(b,"loaded");
c||b&&!c||(b=Zua(a,function(){g.OF(b,"loaded")||(g.PF(b,"loaded","true"),g.WG(a),g.hF(g.ya($ua,a),0))}))},eva=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},fva=function(){if(g.ooa){var a=2,b=g.Fh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Kh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Hh,c)}},I9=function(a,b){u9();
G9()&&G9();Vua(a.id);var c=new g.eJ(H9,a,D9());c.connect(b,ava());c.subscribe("beforeDisconnect",function(a){g.XG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){s9()&&(s9(),F9(null))});
F9(c)},J9=function(){var a=g.fI();
if(!a)return null;var b=w9().Sd();return g.$H(b,a)},K9=function(a){g.OH("remote",a)},L9=function(){var a=s9();
return!!a&&3!=a.getProxyState()},M9=function(){y9()?r9().stopSession():A9("stopSession called before API ready.");
var a=s9();a&&(a.disconnect(1),F9(null))},gva=function(){var a;
a=w9().Uc.$_gos();var b=G9();b&&s9()&&(g.ZH(a,b)||a.push(b));return eva(a)},O9=function(a,b){g.rG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.kC;this.A=this.o=null;this.H=(0,g.A)(this.JK,this);this.F=(0,g.A)(this.Bk,this);this.G=(0,g.A)(this.IK,this);this.J=(0,g.A)(this.WK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.lt,this),hva(this))):c=3;0!=c&&(b?this.lt(c):g.hF((0,g.A)(function(){this.lt(c)},this),0));
var d=cva();d&&N9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},P9=function(a){return new g.UI(a.B.getPlayerContextData())},iva=function(a,b,c,d,e){var f=P9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.YI(f,b,d);g.t(c)&&(g.WI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);Q9(a,"setPlaylist",l);e||R9(a,f)},hva=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.SM,a),this))},a)},jva=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},S9=function(a,b){50>a.C.Dc()&&g.mC(a.C,b)},T9=function(a,b,c){var d=P9(a);
g.WI(d,c);-1E3!=d.g&&(d.g=b);R9(a,d)},Q9=function(a,b,c){a.B.sendMessage(b,c)},R9=function(a,b){jva(a);
a.B.setPlayerContextData(g.ZI(b));hva(a)},N9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Bk(null));
a.A=b;a.A&&(U9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Bk(a.A.media[0]))},kva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=P9(a);b.contentId!=d.videoId&&U9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.WI(d,a.o.getEstimatedTime());R9(a,d)}else U9("No cast media video. Ignoring state update.")},U9=function(a){g.OH("CP",a)},V9=function(a,b,c){return(0,g.A)(function(a){this.bc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.bc("Retrying "+b+" using MDx browser channel."),Q9(this,b,c))},a)},lva=function(a){var b=!1;
r9()||(a=new g.OI(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.AH("yt-remote-cast-available",a);g.XG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){q9("onReceiverSelected: "+a.friendlyName);
g.AH("yt-remote-cast-receiver",a);g.XG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){q9("onReceiverResumed: "+a.friendlyName);
g.AH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){q9("onSessionChange: "+g.WH(a));
a||g.CH("yt-remote-cast-receiver");g.XG("yt-remote-cast2-session-change",a)}),g.u("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
q9("cloudview.createSingleton_: "+b);return b},mva=function(){var a=0<=g.Fb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.GG||a},W9=function(a,b){y9()?r9().setConnectedScreenStatus(a,b):A9("setConnectedScreenStatus called before ready.")},nva=function(){q9("clearCurrentReceiver");
g.CH("yt-remote-cast-receiver")},ova=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){fva();a({command:"cast.sender.init"});return}}if(window.chrome)if(fva(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Dh();55<=b?a="55":50<=b&&(a="50");g.Kh("//www.gstatic.com/eureka/clank"+a+g.Ih,g.Hh)}else g.Lh(0);else g.Hh()},pva=function(a){a?(g.AH("yt-remote-session-app",a.app),g.AH("yt-remote-session-name",a.name)):(g.CH("yt-remote-session-app"),g.CH("yt-remote-session-name"));
g.u("yt.mdx.remote.channelParams_",a,void 0)},qva=function(){var a=D9();
if(g.Sb(a)){var a=g.eI(),b=g.BH("yt-remote-session-name")||"",c=g.BH("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.u("yt.mdx.remote.channelParams_",a,void 0)}},rva=function(){var a=J9();
a?(K9("Resume connection to: "+g.WH(a)),I9(a,0)):(g.nI(),nva(),K9("Skipping connecting because no session screen found."))},sva=function(a){K9("remote.onCastSessionChange_: "+g.WH(a));
if(a){var b=G9();b&&b.id==a.id?W9(b.id,"YouTube TV"):(b&&M9(),I9(a,1))}else s9()&&M9()},tva=function(){var a=gva(),b=G9();
b||(b=J9());return g.$a(a,function(a){return b&&g.TH(b,a.key)?!0:!1})},uva=function(){var a=g.BH("yt-remote-cast-receiver");
return a?a.friendlyName:null},vva=function(a,b,c,d){mva()?lva(b)&&(x9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?bva(a,c):(window.__onGCastApiAvailable=function(b,d){b?bva(a,c):(A9("Failed to load cast API: "+d),z9(!1),x9(!1),g.CH("yt-remote-cast-available"),g.CH("yt-remote-cast-receiver"),Xua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):dva():ova())):q9("Cannot initialize because not running Chrome")},
wva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.yg(a)||"";b&&(this.port=":"+b);this.A=g.xg(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ra(a,"10.0")&&(this.o=!1))},X9=function(a){g.X.call(this,{K:"div",
Y:"ytp-remote",R:[{K:"div",Y:"ytp-remote-display-status",R:[{K:"div",Y:"ytp-remote-display-status-icon",R:[g.DE()]},{K:"div",Y:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",Y:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.ZV(this,250);g.M(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);xva(this,g.yV(a))},xva=function(a,b){if(3==a.A.Xa()){var c;
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR"):b.qb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING"):g.U("YTP_MDX_STATUS_CONNECTED");var d=a.A.Wc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.aW(a.g)},Y9=function(a,b,c){g.L.call(this);
this.H=a;this.W=b;b.addEventListener("onVolumeChange",this.wn,this);b.addEventListener("onCaptionsTrackListChanged",this.jz,this);b.addEventListener("captionschanged",this.Wy,this);b.addEventListener("captionssettingschanged",this.Bs,this);b.addEventListener("videoplayerreset",this.Ek,this);b.addEventListener("mdxautoplaycancel",this.Tu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.zz,this);c.subscribe("remotePlayerChange",this.Dk,this);c.subscribe("remoteQueueChange",this.Ek,this);
c.subscribe("autoplayUpNext",this.Uy,this);c.subscribe("previousNextChange",this.wz,this);c.subscribe("nowAutoplaying",this.mz,this);c.subscribe("autoplayDismissed",this.Ty,this);this.suggestion=null;this.D=new g.iK(64);this.o=new g.lu(this.HA,500,this);g.M(this,this.o);this.A=new g.lu(this.IA,1E3,this);g.M(this,this.A);this.B={};this.G=new g.lu(this.WA,1E3,this);g.M(this,this.G);this.F=new g.tk(this.WR,1E3,this);g.M(this,this.F);this.J=g.y;this.Bs();this.Ek();this.Dk()},Z9=function(a,b){var c=a.H,
d=a.W.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},yva=function(a){Z9(a,0);
a.o.stop();$9(a,new g.iK(64))},c$=function(a,b){if(a$(a)&&!a.C){var c=null;
b&&(c={style:a.W.fl()},g.$b(c,b));a.g.BA(b$(a),c);a.B=P9(a.g).o}},d$=function(a,b){var c=a.W.bf();
c?iva(a.g,b$(a),b,c.Qd(),c.listId.toString()):iva(a.g,b$(a),b);$9(a,new g.iK(1))},zva=function(a,b){if(b){var c=a.W.Wc("captions","tracklist",{qx:1});
c&&c.length?(a.W.Ee("captions","track",b),a.C=!1):(a.W.Zk("captions"),a.C=!0)}else a.W.Ee("captions","track",{})},a$=function(a){return P9(a.g).videoId==b$(a)},b$=function(a){return a.W.getVideoData().videoId},$9=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.V(b,2);if(d!=g.V(a.D,2)){var e=a.W;(e=g.xV(e.app,e.playerType||1))&&g.vU(e,d)}a.D=b;Ava(a.H,c,b)}},e$=function(){var a=tva();
!a&&B9()&&uva()&&(a={key:"cast-selector-receiver",name:uva()});return a},Bva=function(){var a=gva();
B9()&&g.BH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Cva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.yH&&Sua();g.hI();H9||(H9=new wva,g.pI()&&(H9.g="/api/loungedev"));E9||(E9=g.x("yt.mdx.remote.deferredProxies_")||[],g.u("yt.mdx.remote.deferredProxies_",E9,void 0));qva();var c=w9();if(!c){var d=new g.AI(H9);g.u("yt.mdx.remote.screenService_",d,void 0);c=w9();vva(a,d,function(a){a?u9()&&W9(u9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.XG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.x("yt.mdx.remote.initialized_")&&
(g.u("yt.mdx.remote.initialized_",!0,void 0),K9("Initializing: "+g.Lc(b)),f$.push(g.TG("yt-remote-cast2-availability-change",function(){g.XG("yt-remote-receiver-availability-change")})),f$.push(g.TG("yt-remote-cast2-receiver-selected",function(){t9(null);
g.XG("yt-remote-auto-connect","cast-selector-receiver")})),f$.push(g.TG("yt-remote-cast2-receiver-resumed",function(){g.XG("yt-remote-receiver-resumed","cast-selector-receiver")})),f$.push(g.TG("yt-remote-cast2-session-change",sva)),f$.push(g.TG("yt-remote-connection-change",function(a){a?W9(u9(),"YouTube TV"):J9()||(W9(null,null),nva())})),a=D9(),b.isAuto&&(a.id+="#dial"),g.xG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,K9(" -- with channel params: "+g.Lc(a)),
pva(a),c.start(),u9()||rva())},g$=function(){B9()?r9()?y9()?(q9("Requesting cast selector."),r9().requestSession()):(q9("Wait for cast API to be ready to request the session."),C9.push(g.TG("yt-remote-cast2-api-ready",g$))):A9("requestCastSelector: Cast is not initialized."):A9("requestCastSelector: Cast API is not installed!")},h$=function(a){g.VV.call(this,a);
this.A={key:g.YH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.iK(64);this.H=0;var b=g.rV(a).C;b&&(b=b.A&&b.A.g)&&(b=new o9(a,b),g.M(this,b));b=new X9(a);g.M(this,b);g.PV(a,b.element,5)},Ava=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.nU(c,b))},i$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)M9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.bf();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Yb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.tB(),0),currentTime:a.g.getCurrentTime()}}else c=null;K9("Connecting to: "+g.Lc(b));"cast-selector-receiver"==b.key?(t9(c||null),c=c||null,y9()?r9().setLaunchParams(c):A9("setLaunchParams called before ready.")):!c&&L9()&&u9()==b.key?g.XG("yt-remote-connection-change",
!0):(M9(),t9(c||null),c=w9().Sd(),(c=g.$H(c,b.key))&&I9(c,1))}};
g.p(o9,g.yW);o9.prototype.H=function(){var a=this.W.Wc("remote","receivers");a&&1<a.length&&!this.W.Wc("remote","quickCast")?(this.G=g.Bb(a,this.F,this),g.AW(this,(0,g.J)(a,this.F)),a=this.W.Wc("remote","currentReceiver"),g.zW(this,this.F(a)),this.B||(g.N1(this.g,this),this.B=!0)):this.B&&(g.O1(this.g,this),this.B=!1)};
o9.prototype.F=function(a){return a.key};
o9.prototype.Le=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
o9.prototype.gd=function(a){g.yW.prototype.gd.call(this,a);this.W.Ee("remote","currentReceiver",this.G[a]);this.g.Vb()};
g.C(p9,g.aI);g.h=p9.prototype;g.h.Sd=function(a){return this.Uc.$_gs(a)};
g.h.contains=function(a){return!!this.Uc.$_c(a)};
g.h.get=function(a){return this.Uc.$_g(a)};
g.h.start=function(){this.Uc.$_st()};
g.h.so=function(a,b,c){this.Uc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Uc.$_r(a,b,c)};
g.h.eo=function(a,b,c,d){this.Uc.$_un(a,b,c,d)};
g.h.P=function(){for(var a=0,b=this.o.length;a<b;++a)this.Uc.$_ubk(this.o[a]);this.o.length=0;this.Uc=null;p9.O.P.call(this)};
g.h.dQ=function(){this.U("screenChange")};
g.h.yM=function(){this.U("onlineScreenChange")};
var v9=null,C9=[],E9=null,H9=null;g.C(O9,g.rG);g.h=O9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,V9(this,"play")):Q9(this,"play"),T9(this,1,g.XI(P9(this))),this.U("remotePlayerChange")):S9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,V9(this,"pause")):Q9(this,"pause"),T9(this,2,g.XI(P9(this))),this.U("remotePlayerChange")):S9(this,this.pause)};
g.h.hB=function(a){if(1==this.g){if(this.o){var b=P9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,V9(this,"seekTo",{newTime:a}))}else Q9(this,"seekTo",{newTime:a});T9(this,3,a);this.U("remotePlayerChange")}else S9(this,g.ya(this.hB,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,V9(this,"stopVideo")):Q9(this,"stopVideo");var a=P9(this);a.index=-1;a.videoId="";g.VI(a);R9(this,a);this.U("remotePlayerChange")}else S9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=P9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.A)(function(){U9("set receiver volume: "+d)},this),(0,g.A)(function(){this.bc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.A)(function(){U9("set receiver muted: "+b)},this),(0,g.A)(function(){this.bc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Q9(this,"setVolume",e)}c.muted=b;c.volume=a;R9(this,c)}else S9(this,g.ya(this.setVolume,a,b))};
g.h.BA=function(a,b){if(1==this.g){var c=P9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Lc(b.style),g.$b(d,c.o));Q9(this,"setSubtitlesTrack",d);R9(this,c)}else S9(this,g.ya(this.BA,a,b))};
g.h.kt=function(a,b){if(1==this.g){Q9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lc.id});var c=P9(this);c.audioTrackId=b.Lc.id;R9(this,c)}else S9(this,g.ya(this.kt,a,b))};
g.h.gB=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.YI(c,a,b);R9(this,c)}Q9(this,"previous")}else S9(this,g.ya(this.gB,a,b))};
g.h.fB=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.YI(c,a,b);R9(this,c)}Q9(this,"next")}else S9(this,g.ya(this.fB,a,b))};
g.h.Iv=function(){1==this.g?Q9(this,"dismissAutoplay"):S9(this,this.Iv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}O9.O.dispose.call(this)};
g.h.P=function(){jva(this);this.B=null;this.C.clear();N9(this,null);O9.O.P.call(this)};
g.h.lt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.nC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.SM=function(a,b){this.U(a,b)};
g.h.JK=function(a){if(!a)this.Bk(null),N9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=P9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)U9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,R9(this,b)}};
g.h.Bk=function(a){U9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),kva(this),this.U("remotePlayerChange")};
g.h.IK=function(a){a?(kva(this),this.U("remotePlayerChange")):this.Bk(null)};
g.h.WK=function(){var a=cva();a&&N9(this,a)};
g.h.bc=function(a){g.OH("CP",a)};
var f$=[];g.h=wva.prototype;g.h.Hh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Gg(d+a,b||{})};
g.h.jt=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.ya(this.YP,c,!0),onError:g.ya(this.XP,d),fd:g.ya(this.ZP,d)};b&&(c.Ob=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uF(a,c)};
g.h.YP=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.XP=function(a,b){a(Error("Request error: "+b.status))};
g.h.ZP=function(a){a(Error("request timed out"))};
g.p(X9,g.X);X9.prototype.B=function(a){xva(this,a.state)};
g.C(Y9,g.L);g.h=Y9.prototype;
g.h.P=function(){Y9.O.P.call(this);this.o.stop();this.A.stop();this.J();this.W.removeEventListener("onVolumeChange",this.wn,this);this.W.removeEventListener("onCaptionsTrackListChanged",this.jz,this);this.W.removeEventListener("captionschanged",this.Wy,this);this.W.removeEventListener("videoplayerreset",this.Ek,this);this.W.removeEventListener("captionssettingschanged",this.Bs,this);this.W.removeEventListener("mdxautoplaycancel",this.Tu,this);this.g.unsubscribe("proxyStateChange",this.zz,this);this.g.unsubscribe("remotePlayerChange",
this.Dk,this);this.g.unsubscribe("remoteQueueChange",this.Ek,this);this.g.unsubscribe("autoplayUpNext",this.Uy,this);this.g.unsubscribe("previousNextChange",this.wz,this);this.g.unsubscribe("nowAutoplaying",this.mz,this);this.g.unsubscribe("autoplayDismissed",this.Ty,this);this.g=this.H=null};
g.h.WB=function(a,b){2==this.g.g||(a$(this)?this.zG.apply(this,arguments):this.vG.apply(this,arguments))};
g.h.Wy=function(a){this.WB("control_subtitles_set_track",g.Sb(a)?null:a)};
g.h.Bs=function(){var a=this.W.Wc("captions","track");g.Sb(a)||c$(this,a)};
g.h.vG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":d$(this,this.W.getCurrentTime());break;case "control_seek":d$(this,c[0]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.kt(b$(this),c)}};
g.h.zG=function(a,b){if(1081!=P9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":P9(this.g).qb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Mi(c[0],c[1]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.kt(b$(this),c)}}};
g.h.wn=function(a){if(a$(this)){this.g.unsubscribe("remotePlayerChange",this.Dk,this);var b=Math.round(a.volume);a=!!a.muted;var c=P9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Dk,this)}};
g.h.jz=function(){g.Sb(this.B)||zva(this,this.B);this.C=!1};
g.h.zz=function(a,b){this.A.stop();2==b&&this.IA()};
g.h.Dk=function(){if(a$(this)){this.o.stop();var a=P9(this.g);switch(a.g){case 1081:$9(this,new g.iK(8));break;case 1:this.HA();$9(this,new g.iK(8));break;case 1083:case 3:$9(this,new g.iK(9));break;case 0:$9(this,new g.iK(2));this.F.stop();Z9(this,this.W.getVideoData().lengthSeconds);break;case 1082:$9(this,new g.iK(4));break;case 2:$9(this,new g.iK(4));Z9(this,g.XI(a));break;case -1:$9(this,new g.iK(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},$9(this,
new g.iK(128,a))}var a=P9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,zva(this,a));a=P9(this.g);-1==a.volume||Math.round(this.W.getVolume())==a.volume&&this.W.Zd()==a.muted||this.G.isActive()||this.WA()}else yva(this)};
g.h.wz=function(){this.W.U("mdxpreviousnextchange")};
g.h.Ek=function(){a$(this)||yva(this)};
g.h.Tu=function(){this.g.Iv()};
g.h.Uy=function(a){a&&(a=g.uF("/watch_queue_ajax",{method:"GET",Hc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.A)(this.RN,this)}))&&(this.J=(0,g.A)(a.abort,a))};
g.h.RN=function(a,b){var c=new g.RQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.W.U("mdxautoplayupnext",c)};
g.h.mz=function(a){(0,window.isNaN)(a)||this.W.U("mdxnowautoplaying",a)};
g.h.Ty=function(){this.W.U("mdxautoplaycanceled")};
g.h.WR=function(a,b){-1==P9(this.g).g?d$(this,a):b&&this.g.hB(a)};
g.h.WA=function(){if(a$(this)){var a=P9(this.g);this.W.removeEventListener("onVolumeChange",this.wn,this);a.muted?this.W.mute():this.W.yg();this.W.setVolume(a.volume);this.W.addEventListener("onVolumeChange",this.wn,this)}};
g.h.HA=function(){this.o.stop();if(!this.g.la()){var a=P9(this.g);a.qb()&&$9(this,new g.iK(8));Z9(this,g.XI(a));this.o.start()}};
g.h.IA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.C(h$,g.VV);g.h=h$.prototype;g.h.create=function(){Cva("embedded"==g.Y(this.g).g);this.D.push(g.TG("yt-remote-before-disconnect",this.FK,this));this.D.push(g.TG("yt-remote-connection-change",this.bN,this));this.D.push(g.TG("yt-remote-receiver-availability-change",this.xz,this));this.D.push(g.TG("yt-remote-auto-connect",this.ZM,this));this.D.push(g.TG("yt-remote-receiver-resumed",this.YM,this));this.xz()};
g.h.load=function(){this.g.Cp();h$.O.load.call(this);this.C=new Y9(this,this.g,this.o);var a;a=(a=ava())?a.currentTime:0;var b=L9()?new O9(s9(),void 0):null;0==a&&b&&(a=g.XI(P9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));Ava(this,this.F,this.F);g.M2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Ve(this.C,this.o);this.o=this.C=null;h$.O.unload.call(this);g.M2(this.g.app,5)};
g.h.P=function(){(0,g.l2)(this.D);h$.O.P.call(this)};
g.h.ll=function(a,b){this.loaded&&this.C.WB.apply(this.C,arguments)};
g.h.aG=function(){return this.loaded?this.C.suggestion:null};
g.h.Bf=function(){return this.o?P9(this.o).Bf:!1};
g.h.hasNext=function(){return this.o?P9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.AR=function(){var a=P9(this.o),b=this.g.getVideoData(),c=this.g.Dd(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.F)()-a.A)/1E3:a.B;var l=1>=Rua(a)-this.getCurrentTime(),m=a.J,n=Rua(a),a=0<a.C?a.C+((0,g.F)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.CR=function(){this.o&&this.o.fB()};
g.h.DR=function(){this.o&&this.o.gB()};
g.h.FK=function(a){1==a&&(this.J=this.o?P9(this.o):null)};
g.h.bN=function(){var a=L9()?new O9(s9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ue(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.qB(a.videoId,g.XI(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.xz=function(){this.G=[this.A].concat(Bva());var a=e$()||this.A;i$(this,a);this.g.xa("onMdxReceiversChange")};
g.h.ZM=function(){var a=e$();i$(this,a)};
g.h.YM=function(){this.B=e$()};
g.h.zR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?g$():i$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&g$(),!0):!1}};
g.h.ER=function(){Q9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ze=function(){return!1};
window._exportCheck==g.Aa&&g.u("ytmod.player.remote",h$,void 0);})(_yt_player);
