source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

# front-end
gem 'sass'
gem 'compass'

gem 'bcrypt'

# testing
group :test do
  gem 'faker'
  gem 'rspec'
end
